#!/usr/bin/env -S uv run --python 3.12
# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///

"""Curate Rootstock diff reports using GitLab Duo CLI."""

from __future__ import annotations

import argparse
from collections import Counter
from dataclasses import dataclass
from datetime import UTC, datetime
import hashlib
import json
from json import JSONDecodeError
from pathlib import Path
import re
import subprocess
import sys
import time

EXIT_SUCCESS = 0
EXIT_ERROR = 1

BASE_BRANCH = "main"
DEFAULT_OUTPUT_DIR = Path(".rootstock") / "reports"
CURATION_PROTOCOL_RELATIVE = (
    Path(".cursor") / "skills" / "rootstock" / "resources" / "curation-protocol.md"
)
DATE_FORMAT = "%Y-%m-%d"
PROMPT_MAX_CHARS = 100_000
GIT_TIMEOUT_SECONDS = 120
DUO_TIMEOUT_SECONDS = 120
DUO_VERSION_TIMEOUT_SECONDS = 10
DEFAULT_DELAY_SECONDS = 5.0

DUO_INSTALL_MESSAGE = (
    "GitLab Duo CLI not found. Install: npm install -g @gitlab-org/duo-cli. "
    "Requires GL_TOKEN environment variable with api scope."
)

GOAL_SUMMARY = (
    "Classify and evaluate the following .cursor environment changes against the curation "
    "protocol. Return structured JSON decisions."
)

CLASSIFICATION_ALIASES = {
    "evolution": "Evolution",
    "newartifact": "NewArtifact",
    "new artifact": "NewArtifact",
    "scriptchange": "ScriptChange",
    "script change": "ScriptChange",
    "reorganization": "Reorganization",
    "reorganization candidate": "Reorganization",
    "regression": "Regression",
    "prune": "Prune",
    "prune candidate": "Prune",
}

RECOMMENDATION_ALIASES = {
    "accept": "accept",
    "revise": "revise",
    "reject": "reject",
    "move": "move",
    "prune": "prune",
}

DECISION_RECOMMENDATIONS = ["accept", "revise", "reject", "move", "prune"]
PROTOCOL_SECTIONS_TO_INCLUDE = [
    "Classification Taxonomy",
    "Quality Rubric",
    "Structured Output Contract",
]


@dataclass(frozen=True)
class DiffChange:
    """Single changed artifact record from diff report."""

    change_id: str
    path: str
    operation: str
    artifact_type: str
    diff_content: str
    canonical_neighbors: list[str]


@dataclass(frozen=True)
class DiffGroup:
    """Group of changes to be curated together."""

    group_id: str
    artifact_type: str
    changes: list[DiffChange]


def emit_json(payload: dict[str, object]) -> None:
    """Emit machine-readable JSON payload to stdout."""
    print(json.dumps(payload, indent=2))


def log(message: str) -> None:
    """Emit human-readable status to stderr."""
    sys.stderr.write(f"{message}\n")


def fail(message: str, payload: dict[str, object] | None = None) -> int:
    """Emit standardized error payload and stderr message."""
    result = payload if payload is not None else {}
    result["status"] = "error"
    result["error"] = message
    emit_json(result)
    log(f"ERROR: {message}")
    return EXIT_ERROR


def parse_args(argv: list[str]) -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(
        prog="curate.py",
        description=(
            "Run GitLab Duo curation over a Rootstock diff report and emit structured "
            "curation decisions."
        ),
    )
    parser.add_argument(
        "--diff-report",
        type=Path,
        required=True,
        help="Path to JSON diff report generated by diff.py.",
    )
    parser.add_argument(
        "--rootstock-repo",
        type=Path,
        required=True,
        help="Path to local Rootstock repository clone.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        help="Directory for curation reports (default: .rootstock/reports/ under rootstock repo).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Build prompts and write previews without invoking Duo CLI.",
    )
    parser.add_argument(
        "--delay-seconds",
        type=float,
        default=DEFAULT_DELAY_SECONDS,
        help="Delay between Duo calls in seconds (default: 5.0).",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Enable verbose logs.",
    )
    return parser.parse_args(argv)


def ensure_directory(path: Path, label: str) -> None:
    """Validate that a path exists and is a directory."""
    if not path.exists():
        raise ValueError(f"{label} does not exist: {path}")
    if not path.is_dir():
        raise ValueError(f"{label} is not a directory: {path}")


def ensure_file(path: Path, label: str) -> None:
    """Validate that a path exists and is a file."""
    if not path.exists():
        raise ValueError(f"{label} does not exist: {path}")
    if not path.is_file():
        raise ValueError(f"{label} is not a file: {path}")


def run_git(
    repo_path: Path,
    args: list[str],
    verbose: bool,
    allow_failure: bool = False,
) -> subprocess.CompletedProcess[str]:
    """Run a git command and return the completed process."""
    command = ["git", *args]
    if verbose:
        log(f"[git] {repo_path}: {' '.join(command)}")
    try:
        completed = subprocess.run(
            command,
            cwd=repo_path,
            capture_output=True,
            text=True,
            check=False,
            encoding="utf-8",
            errors="replace",
            timeout=GIT_TIMEOUT_SECONDS,
        )
    except subprocess.TimeoutExpired as exc:
        raise RuntimeError(
            f"git {' '.join(args)} timed out after {GIT_TIMEOUT_SECONDS}s"
        ) from exc
    if completed.returncode == 0:
        return completed
    if allow_failure:
        return completed
    details = extract_process_error(completed)
    raise RuntimeError(f"git {' '.join(args)} failed: {details}")


def ensure_git_repository(repo_path: Path, verbose: bool) -> None:
    """Validate that path is a git work tree."""
    completed = run_git(
        repo_path=repo_path,
        args=["rev-parse", "--is-inside-work-tree"],
        verbose=verbose,
        allow_failure=True,
    )
    if completed.returncode != 0:
        raise ValueError(f"Not a git repository: {repo_path}")
    if completed.stdout.strip().lower() != "true":
        raise ValueError(f"Path is not inside a git work tree: {repo_path}")


def branch_exists(repo_path: Path, branch: str, verbose: bool) -> bool:
    """Check whether a local branch exists."""
    completed = run_git(
        repo_path=repo_path,
        args=["show-ref", "--verify", "--quiet", f"refs/heads/{branch}"],
        verbose=verbose,
        allow_failure=True,
    )
    return completed.returncode == 0


def ensure_duo_cli_available() -> None:
    """Validate that duo CLI is installed and callable."""
    try:
        completed = subprocess.run(
            ["duo", "--version"],
            capture_output=True,
            text=True,
            check=False,
            encoding="utf-8",
            errors="replace",
            timeout=DUO_VERSION_TIMEOUT_SECONDS,
        )
    except FileNotFoundError as exc:
        raise ValueError(DUO_INSTALL_MESSAGE) from exc
    except subprocess.TimeoutExpired as exc:
        raise ValueError(
            f"{DUO_INSTALL_MESSAGE} Duo --version timed out after {DUO_VERSION_TIMEOUT_SECONDS}s."
        ) from exc
    if completed.returncode == 0:
        return
    details = extract_process_error(completed)
    raise ValueError(f"{DUO_INSTALL_MESSAGE} Duo check output: {details}")


def extract_process_error(process: subprocess.CompletedProcess[str]) -> str:
    """Extract concise process error details."""
    stderr = process.stderr.strip()
    stdout = process.stdout.strip()
    details = stderr if stderr != "" else stdout
    if details == "":
        return "command failed without output"
    return details


def resolve_output_dir(rootstock_repo: Path, output_dir: Path | None) -> Path:
    """Resolve report output directory."""
    if output_dir is None:
        return rootstock_repo / DEFAULT_OUTPUT_DIR
    if output_dir.is_absolute():
        return output_dir
    return rootstock_repo / output_dir


def parse_diff_report(diff_report_path: Path) -> tuple[dict[str, str], list[DiffGroup]]:
    """Parse and validate diff report data."""
    try:
        report_data = json.loads(diff_report_path.read_text(encoding="utf-8"))
    except JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON diff report: {diff_report_path}: {exc}") from exc
    if not isinstance(report_data, dict):
        raise ValueError("Diff report root must be a JSON object.")

    metadata_raw = report_data.get("metadata")
    if not isinstance(metadata_raw, dict):
        raise ValueError("Diff report missing metadata object.")
    contributor = str(metadata_raw.get("contributor", "")).strip()
    branch = str(metadata_raw.get("branch", "")).strip()
    base = str(metadata_raw.get("base", "")).strip()
    if contributor == "":
        raise ValueError("Diff report metadata.contributor is required.")
    if branch == "":
        raise ValueError("Diff report metadata.branch is required.")
    if base == "":
        raise ValueError("Diff report metadata.base is required.")
    metadata = {"contributor": contributor, "branch": branch, "base": base}

    groups_raw = report_data.get("change_groups")
    if not isinstance(groups_raw, list):
        raise ValueError("Diff report missing change_groups array.")

    groups: list[DiffGroup] = []
    for group_index, group_raw in enumerate(groups_raw):
        if not isinstance(group_raw, dict):
            raise ValueError(f"change_groups[{group_index}] must be an object.")
        group_id = str(group_raw.get("group_id", "")).strip()
        if group_id == "":
            raise ValueError(f"change_groups[{group_index}] missing group_id.")
        group_artifact_type = str(group_raw.get("artifact_type", "")).strip()
        if group_artifact_type == "":
            group_artifact_type = "config"

        changes_raw = group_raw.get("changes")
        if not isinstance(changes_raw, list):
            raise ValueError(f"change_groups[{group_index}] missing changes array.")

        parsed_changes: list[DiffChange] = []
        for change_index, change_raw in enumerate(changes_raw):
            if not isinstance(change_raw, dict):
                raise ValueError(
                    f"change_groups[{group_index}].changes[{change_index}] must be an object."
                )
            path = str(change_raw.get("path", "")).strip()
            operation = str(change_raw.get("operation", "")).strip()
            artifact_type = str(change_raw.get("artifact_type", "")).strip()
            diff_content = str(change_raw.get("diff_content", ""))
            neighbors_raw = change_raw.get("canonical_neighbors", [])

            if path == "":
                raise ValueError(
                    f"change_groups[{group_index}].changes[{change_index}] missing path."
                )
            if operation == "":
                raise ValueError(
                    f"change_groups[{group_index}].changes[{change_index}] missing operation."
                )
            if artifact_type == "":
                artifact_type = group_artifact_type
            if not isinstance(neighbors_raw, list):
                raise ValueError(
                    f"change_groups[{group_index}].changes[{change_index}] "
                    "canonical_neighbors must be an array."
                )
            canonical_neighbors = [str(item).strip() for item in neighbors_raw if str(item).strip() != ""]
            change_id = stable_change_id(path=path, operation=operation, diff_content=diff_content)
            parsed_changes.append(
                DiffChange(
                    change_id=change_id,
                    path=path,
                    operation=operation,
                    artifact_type=artifact_type,
                    diff_content=diff_content,
                    canonical_neighbors=canonical_neighbors,
                )
            )

        groups.append(
            DiffGroup(
                group_id=group_id,
                artifact_type=group_artifact_type,
                changes=parsed_changes,
            )
        )

    return metadata, groups


def stable_change_id(path: str, operation: str, diff_content: str) -> str:
    """Build stable change identifier from path and diff hash."""
    digest_input = f"{path}\n{operation}\n{diff_content}"
    digest = hashlib.sha256(digest_input.encode("utf-8")).hexdigest()[:16]
    return f"{path}#{digest}"


def extract_markdown_section(markdown_text: str, heading_name: str) -> str:
    """Extract a top-level markdown section by heading text."""
    heading = f"## {heading_name}"
    lines = markdown_text.splitlines()
    start_index: int | None = None
    for index, line in enumerate(lines):
        if line.strip() == heading:
            start_index = index
            break
    if start_index is None:
        raise ValueError(f"Missing protocol section: {heading_name}")

    end_index = len(lines)
    for index in range(start_index + 1, len(lines)):
        if lines[index].startswith("## "):
            end_index = index
            break
    section = "\n".join(lines[start_index:end_index]).strip()
    if section == "":
        raise ValueError(f"Protocol section is empty: {heading_name}")
    return section


def build_protocol_summary(protocol_text: str) -> str:
    """Build condensed protocol payload for prompt inclusion."""
    sections: list[str] = []
    for heading in PROTOCOL_SECTIONS_TO_INCLUDE:
        sections.append(extract_markdown_section(protocol_text, heading))
    return "\n\n".join(sections).strip()


def load_canonical_neighbor_content(
    repo_path: Path,
    group: DiffGroup,
    verbose: bool,
) -> dict[str, str]:
    """Load canonical neighbor file content from main branch for one group."""
    unique_neighbors: set[str] = set()
    for change in group.changes:
        unique_neighbors.update(change.canonical_neighbors)

    neighbors: dict[str, str] = {}
    for neighbor_path in sorted(unique_neighbors):
        completed = run_git(
            repo_path=repo_path,
            args=["show", f"{BASE_BRANCH}:{neighbor_path}"],
            verbose=verbose,
            allow_failure=True,
        )
        if completed.returncode != 0:
            neighbors[neighbor_path] = (
                f"[Unable to load canonical file from {BASE_BRANCH}: "
                f"{extract_process_error(completed)}]"
            )
            continue
        neighbors[neighbor_path] = completed.stdout
    return neighbors


def render_canonical_context(content_by_path: dict[str, str]) -> str:
    """Render canonical context block for prompt."""
    if not content_by_path:
        return "No canonical neighbor files were provided for this group."
    sections: list[str] = []
    for path_text in sorted(content_by_path.keys()):
        file_content = content_by_path[path_text].rstrip("\n")
        sections.append(
            f"### {path_text}\n"
            f"```text\n{file_content}\n```"
        )
    return "\n\n".join(sections)


def render_change_block(change: DiffChange) -> str:
    """Render one changed artifact block for prompt inclusion."""
    body = change.diff_content.rstrip("\n")
    return (
        f"### Change ID: {change.change_id}\n"
        f"- Path: {change.path}\n"
        f"- Operation: {change.operation}\n"
        f"- Artifact Type: {change.artifact_type}\n"
        f"- Canonical neighbors listed in diff report: {len(change.canonical_neighbors)}\n"
        f"```text\n{body}\n```"
    )


def truncate_text(text: str, max_chars: int) -> str:
    """Return text truncated to max chars with marker when needed."""
    if max_chars <= 0:
        return ""
    if len(text) <= max_chars:
        return text
    marker = "\n\n[... truncated for token budget ...]\n"
    if len(marker) >= max_chars:
        return text[:max_chars]
    keep = max_chars - len(marker)
    return text[:keep] + marker


def render_prompt(
    protocol_summary: str,
    canonical_context: str,
    contributor: str,
    branch: str,
    group_id: str,
    change_blocks: list[str],
) -> str:
    """Render complete curation prompt text."""
    changes_text = "\n\n".join(change_blocks)
    return (
        "You are the curator of a shared knowledge base for AI-assisted development. "
        "Your job is to classify and evaluate changes against the canonical knowledge base.\n\n"
        "## Curation Protocol\n\n"
        f"{protocol_summary}\n\n"
        "## Canonical Context\n\n"
        "The following files exist in the canonical environment alongside the changes being evaluated:\n\n"
        f"{canonical_context}\n\n"
        "## Changes to Evaluate\n\n"
        f'The following changes were made by contributor "{contributor}" on branch "{branch}" '
        f"for group \"{group_id}\":\n\n"
        f"{changes_text}\n\n"
        "## Instructions\n\n"
        "For each change above, produce a JSON object following the structured output contract. "
        "Return a JSON array of decision objects. Do not include any text outside the JSON array."
    )


def build_prompt_chunks(
    protocol_summary: str,
    canonical_context: str,
    contributor: str,
    branch: str,
    group: DiffGroup,
) -> list[tuple[list[DiffChange], str]]:
    """Build prompt chunks constrained by character budget."""
    change_blocks = [render_change_block(change) for change in group.changes]
    short_context = canonical_context

    if not change_blocks:
        empty_prompt = render_prompt(
            protocol_summary=protocol_summary,
            canonical_context=short_context,
            contributor=contributor,
            branch=branch,
            group_id=group.group_id,
            change_blocks=[],
        )
        return [([], truncate_text(empty_prompt, PROMPT_MAX_CHARS))]

    template_without_changes = render_prompt(
        protocol_summary=protocol_summary,
        canonical_context=short_context,
        contributor=contributor,
        branch=branch,
        group_id=group.group_id,
        change_blocks=[],
    )
    if len(template_without_changes) >= PROMPT_MAX_CHARS:
        margin = 5_000
        allowed_context_chars = max(
            1_000,
            PROMPT_MAX_CHARS - len(
                render_prompt(
                    protocol_summary=protocol_summary,
                    canonical_context="",
                    contributor=contributor,
                    branch=branch,
                    group_id=group.group_id,
                    change_blocks=[],
                )
            ) - margin,
        )
        short_context = truncate_text(canonical_context, allowed_context_chars)

    chunks: list[tuple[list[DiffChange], str]] = []
    current_changes: list[DiffChange] = []
    current_blocks: list[str] = []
    for change, block in zip(group.changes, change_blocks, strict=True):
        candidate_blocks = [*current_blocks, block]
        candidate_prompt = render_prompt(
            protocol_summary=protocol_summary,
            canonical_context=short_context,
            contributor=contributor,
            branch=branch,
            group_id=group.group_id,
            change_blocks=candidate_blocks,
        )
        if len(candidate_prompt) <= PROMPT_MAX_CHARS:
            current_changes.append(change)
            current_blocks.append(block)
            continue

        if current_blocks:
            committed_prompt = render_prompt(
                protocol_summary=protocol_summary,
                canonical_context=short_context,
                contributor=contributor,
                branch=branch,
                group_id=group.group_id,
                change_blocks=current_blocks,
            )
            chunks.append((current_changes, committed_prompt))
            current_changes = []
            current_blocks = []

        single_prompt = render_prompt(
            protocol_summary=protocol_summary,
            canonical_context=short_context,
            contributor=contributor,
            branch=branch,
            group_id=group.group_id,
            change_blocks=[block],
        )
        if len(single_prompt) <= PROMPT_MAX_CHARS:
            current_changes = [change]
            current_blocks = [block]
            continue

        truncated_block = truncate_text(block, max_chars=max(2_000, PROMPT_MAX_CHARS // 2))
        forced_prompt = render_prompt(
            protocol_summary=protocol_summary,
            canonical_context=short_context,
            contributor=contributor,
            branch=branch,
            group_id=group.group_id,
            change_blocks=[truncated_block],
        )
        chunks.append(([change], truncate_text(forced_prompt, PROMPT_MAX_CHARS)))

    if current_blocks:
        final_prompt = render_prompt(
            protocol_summary=protocol_summary,
            canonical_context=short_context,
            contributor=contributor,
            branch=branch,
            group_id=group.group_id,
            change_blocks=current_blocks,
        )
        chunks.append((current_changes, final_prompt))

    return chunks


def slugify(value: str) -> str:
    """Build filesystem-safe token."""
    slug = re.sub(r"[^A-Za-z0-9._-]+", "-", value.strip()).strip("-")
    if slug == "":
        return "group"
    return slug


def write_prompt_preview(
    prompt_dir: Path,
    contributor: str,
    group_id: str,
    chunk_index: int,
    prompt_text: str,
) -> Path:
    """Persist prompt text for inspection."""
    prompt_dir.mkdir(parents=True, exist_ok=True)
    file_name = (
        f"{slugify(contributor)}-curate-prompt-{slugify(group_id)}-{chunk_index:02d}.txt"
    )
    prompt_path = prompt_dir / file_name
    prompt_path.write_text(prompt_text, encoding="utf-8")
    return prompt_path


def call_duo(prompt_text: str, verbose: bool) -> str:
    """Invoke Duo CLI and return stdout."""
    if verbose:
        log(f"[duo] invoking with prompt chars={len(prompt_text)}")
    try:
        completed = subprocess.run(
            ["duo", "run", "--goal", GOAL_SUMMARY],
            input=prompt_text,
            capture_output=True,
            text=True,
            timeout=DUO_TIMEOUT_SECONDS,
            check=False,
            encoding="utf-8",
            errors="replace",
        )
    except subprocess.TimeoutExpired as exc:
        raise RuntimeError(f"Duo CLI timed out after {DUO_TIMEOUT_SECONDS} seconds.") from exc
    if completed.returncode == 0:
        return completed.stdout
    details = extract_process_error(completed)
    raise RuntimeError(f"Duo CLI failed: {details}")


def extract_json_array(raw_text: str) -> list[object]:
    """Extract first valid JSON array from potentially mixed text."""
    stripped = raw_text.strip()
    if stripped == "":
        raise ValueError("Duo response was empty.")
    try:
        decoded = json.loads(stripped)
        if isinstance(decoded, list):
            return decoded
    except JSONDecodeError:
        pass

    decoder = json.JSONDecoder()
    for index, character in enumerate(raw_text):
        if character != "[":
            continue
        try:
            decoded, _ = decoder.raw_decode(raw_text[index:])
        except JSONDecodeError:
            continue
        if isinstance(decoded, list):
            return decoded
    raise ValueError("Duo response did not contain a JSON array.")


def normalize_classification(raw_value: object) -> str | None:
    """Normalize classification aliases to schema values."""
    if not isinstance(raw_value, str):
        return None
    key = raw_value.strip().lower()
    return CLASSIFICATION_ALIASES.get(key)


def normalize_recommendation(raw_value: object) -> str | None:
    """Normalize recommendation aliases to schema values."""
    if not isinstance(raw_value, str):
        return None
    key = raw_value.strip().lower()
    return RECOMMENDATION_ALIASES.get(key)


def normalize_confidence(raw_value: object) -> float | None:
    """Normalize confidence to 0.0-1.0 float."""
    if isinstance(raw_value, int | float):
        confidence = float(raw_value)
    elif isinstance(raw_value, str):
        text = raw_value.strip()
        if text == "":
            return None
        try:
            confidence = float(text)
        except ValueError:
            return None
    else:
        return None
    if confidence < 0.0 or confidence > 1.0:
        return None
    return confidence


def normalize_string_list(raw_value: object) -> list[str] | None:
    """Normalize JSON string array values."""
    if raw_value is None:
        return []
    if not isinstance(raw_value, list):
        return None
    normalized: list[str] = []
    for item in raw_value:
        if not isinstance(item, str):
            return None
        text = item.strip()
        if text == "":
            continue
        normalized.append(text)
    return normalized


def fallback_decision(change: DiffChange, reason: str) -> dict[str, object]:
    """Build conservative fallback decision for parsing failures."""
    return {
        "change_id": change.change_id,
        "artifact_path": change.path,
        "artifact_type": change.artifact_type,
        "classification": "Evolution",
        "recommendation": "revise",
        "confidence": 0.0,
        "target_location": None,
        "rationale": [reason],
        "violations": ["Failed to parse Duo response"],
        "requires_human_review": True,
    }


def dry_run_fallback_decision(change: DiffChange) -> dict[str, object]:
    """Build conservative decision placeholder in dry-run mode."""
    return {
        "change_id": change.change_id,
        "artifact_path": change.path,
        "artifact_type": change.artifact_type,
        "classification": "Evolution",
        "recommendation": "revise",
        "confidence": 0.0,
        "target_location": None,
        "rationale": ["Dry-run mode: Duo invocation skipped."],
        "violations": ["Dry-run mode: no model-generated decision."],
        "requires_human_review": True,
    }


def validate_duo_decision(
    raw_decision: object,
    expected_change: DiffChange,
) -> dict[str, object]:
    """Validate and normalize one Duo decision object."""
    if not isinstance(raw_decision, dict):
        raise ValueError("Decision is not a JSON object.")

    classification = normalize_classification(raw_decision.get("classification"))
    if classification is None:
        raise ValueError("classification is missing or invalid.")

    recommendation = normalize_recommendation(raw_decision.get("recommendation"))
    if recommendation is None:
        raise ValueError("recommendation is missing or invalid.")

    confidence = normalize_confidence(raw_decision.get("confidence"))
    if confidence is None:
        raise ValueError("confidence is missing or invalid.")

    rationale = normalize_string_list(raw_decision.get("rationale"))
    if rationale is None:
        raise ValueError("rationale must be an array of strings.")
    if not rationale:
        raise ValueError("rationale cannot be empty.")

    violations = normalize_string_list(raw_decision.get("violations"))
    if violations is None:
        raise ValueError("violations must be an array of strings.")

    raw_path = str(raw_decision.get("artifact_path", "")).strip()
    artifact_path = expected_change.path if raw_path == "" else raw_path

    raw_change_id = str(raw_decision.get("change_id", "")).strip()
    if raw_change_id == "":
        raise ValueError("change_id is required.")
    if raw_change_id != expected_change.change_id:
        raise ValueError(
            f"change_id mismatch. expected={expected_change.change_id} got={raw_change_id}"
        )

    raw_target = raw_decision.get("target_location")
    target_location: str | None
    if raw_target is None:
        target_location = None
    elif isinstance(raw_target, str):
        target_location = raw_target.strip() or None
    else:
        raise ValueError("target_location must be string or null.")

    if recommendation == "move" and target_location is None:
        raise ValueError("target_location is required when recommendation=move.")
    if recommendation != "move":
        target_location = None

    raw_review = raw_decision.get("requires_human_review")
    if isinstance(raw_review, bool):
        requires_human_review = raw_review or confidence < 0.7
    else:
        requires_human_review = confidence < 0.7

    return {
        "change_id": expected_change.change_id,
        "artifact_path": artifact_path,
        "artifact_type": expected_change.artifact_type,
        "classification": classification,
        "recommendation": recommendation,
        "confidence": confidence,
        "target_location": target_location,
        "rationale": rationale,
        "violations": violations,
        "requires_human_review": requires_human_review,
    }


def parse_group_decisions(
    duo_output: str,
    expected_changes: list[DiffChange],
) -> tuple[list[dict[str, object]], list[str]]:
    """Parse and validate Duo decisions for one prompt chunk."""
    warnings: list[str] = []
    raw_items = extract_json_array(duo_output)

    expected_by_id = {change.change_id: change for change in expected_changes}
    parsed_by_id: dict[str, dict[str, object]] = {}

    for index, raw_item in enumerate(raw_items):
        if not isinstance(raw_item, dict):
            warnings.append(f"decision[{index}] ignored: not an object.")
            continue
        change_id = str(raw_item.get("change_id", "")).strip()
        if change_id == "":
            warnings.append(f"decision[{index}] ignored: missing change_id.")
            continue
        expected_change = expected_by_id.get(change_id)
        if expected_change is None:
            warnings.append(
                f"decision[{index}] ignored: change_id not in prompt chunk ({change_id})."
            )
            continue
        if change_id in parsed_by_id:
            warnings.append(f"decision[{index}] ignored: duplicate change_id ({change_id}).")
            continue
        try:
            parsed_by_id[change_id] = validate_duo_decision(raw_item, expected_change)
        except ValueError as exc:
            warnings.append(f"decision[{index}] malformed for {change_id}: {exc}")

    decisions: list[dict[str, object]] = []
    for change in expected_changes:
        decision = parsed_by_id.get(change.change_id)
        if decision is not None:
            decisions.append(decision)
            continue
        decisions.append(fallback_decision(change, "Failed to parse Duo response for this change."))

    return decisions, warnings


def recommendation_counts(decisions: list[dict[str, object]]) -> dict[str, int]:
    """Compute recommendation histogram with full key set."""
    counts = Counter(str(decision.get("recommendation", "")) for decision in decisions)
    result: dict[str, int] = {}
    for recommendation in DECISION_RECOMMENDATIONS:
        result[recommendation] = counts.get(recommendation, 0)
    return result


def build_markdown_summary(report: dict[str, object]) -> str:
    """Build human-readable curation markdown summary."""
    metadata = report.get("metadata", {})
    decisions = report.get("decisions", [])
    if not isinstance(metadata, dict) or not isinstance(decisions, list):
        raise ValueError("Invalid report structure for markdown generation.")

    contributor = str(metadata.get("contributor", "unknown"))
    branch = str(metadata.get("branch", "unknown"))
    timestamp = str(metadata.get("timestamp", ""))
    by_recommendation = metadata.get("by_recommendation", {})
    requires_review_count = metadata.get("requires_review_count", 0)

    lines: list[str] = []
    lines.append(f"# Curation Report: {contributor}")
    lines.append("")
    lines.append(f"- Branch: `{branch}`")
    lines.append(f"- Generated: `{timestamp}`")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Recommendation | Count |")
    lines.append("|---|---:|")
    if isinstance(by_recommendation, dict):
        for recommendation in DECISION_RECOMMENDATIONS:
            lines.append(
                f"| {recommendation} | {int(by_recommendation.get(recommendation, 0))} |"
            )
    lines.append(f"| requires_human_review | {int(requires_review_count)} |")
    lines.append("")
    lines.append("## Decisions")
    lines.append("")

    for decision in decisions:
        if not isinstance(decision, dict):
            continue
        change_id = str(decision.get("change_id", ""))
        artifact_path = str(decision.get("artifact_path", ""))
        artifact_type = str(decision.get("artifact_type", ""))
        classification = str(decision.get("classification", ""))
        recommendation = str(decision.get("recommendation", ""))
        confidence = float(decision.get("confidence", 0.0))
        requires_review = bool(decision.get("requires_human_review", True))
        rationale = decision.get("rationale", [])
        violations = decision.get("violations", [])
        target_location = decision.get("target_location")

        lines.append(f"### {change_id}")
        lines.append(f"- Artifact: `{artifact_path}` ({artifact_type})")
        lines.append(f"- Classification: `{classification}`")
        lines.append(f"- Recommendation: `{recommendation}`")
        lines.append(f"- Confidence: `{confidence:.2f}`")
        lines.append(f"- Requires review: `{str(requires_review).lower()}`")
        if target_location is not None:
            lines.append(f"- Target location: `{target_location}`")
        if isinstance(rationale, list) and rationale:
            lines.append("- Rationale:")
            for item in rationale:
                lines.append(f"  - {item}")
        if isinstance(violations, list) and violations:
            lines.append("- Violations:")
            for item in violations:
                lines.append(f"  - {item}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def write_report_files(
    output_dir: Path,
    contributor: str,
    report: dict[str, object],
) -> tuple[Path, Path]:
    """Write JSON and markdown curation reports."""
    output_dir.mkdir(parents=True, exist_ok=True)
    date_token = datetime.now(UTC).strftime(DATE_FORMAT)
    file_stem = f"{slugify(contributor)}-curation-{date_token}"
    json_path = output_dir / f"{file_stem}.json"
    markdown_path = output_dir / f"{file_stem}.md"

    json_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    markdown_path.write_text(build_markdown_summary(report), encoding="utf-8")
    return json_path, markdown_path


def build_report(
    metadata: dict[str, str],
    decisions: list[dict[str, object]],
) -> dict[str, object]:
    """Build top-level curation report structure."""
    total_decisions = len(decisions)
    by_recommendation = recommendation_counts(decisions)
    requires_review_count = sum(
        1 for item in decisions if bool(item.get("requires_human_review", False))
    )
    return {
        "metadata": {
            "contributor": metadata["contributor"],
            "branch": metadata["branch"],
            "base": metadata["base"],
            "timestamp": datetime.now(UTC).isoformat(),
            "backend": "duo-cli",
            "total_decisions": total_decisions,
            "by_recommendation": by_recommendation,
            "requires_review_count": requires_review_count,
        },
        "decisions": decisions,
    }


def main(argv: list[str] | None = None) -> int:
    """CLI entrypoint."""
    args = parse_args(sys.argv[1:] if argv is None else argv)
    payload: dict[str, object] = {}
    try:
        if args.delay_seconds < 0:
            raise ValueError("--delay-seconds cannot be negative.")

        diff_report_path = args.diff_report.resolve()
        rootstock_repo = args.rootstock_repo.resolve()
        output_dir = resolve_output_dir(rootstock_repo, args.output_dir)
        protocol_path = rootstock_repo / CURATION_PROTOCOL_RELATIVE

        ensure_file(diff_report_path, "--diff-report")
        ensure_directory(rootstock_repo, "--rootstock-repo")
        ensure_file(protocol_path, "curation protocol")
        ensure_git_repository(rootstock_repo, args.verbose)
        if not branch_exists(rootstock_repo, BASE_BRANCH, args.verbose):
            raise ValueError("Local base branch 'main' does not exist in rootstock repo.")
        ensure_duo_cli_available()

        metadata, groups = parse_diff_report(diff_report_path)
        protocol_summary = build_protocol_summary(protocol_path.read_text(encoding="utf-8"))
        output_dir.mkdir(parents=True, exist_ok=True)

        prompt_dir = output_dir / "prompts"
        prompt_files: list[str] = []
        all_decisions: list[dict[str, object]] = []
        all_warnings: list[str] = []
        duo_call_count = 0

        for group_index, group in enumerate(groups):
            log(f"Curating group {group.group_id}...")
            canonical_content = load_canonical_neighbor_content(rootstock_repo, group, args.verbose)
            canonical_context = render_canonical_context(canonical_content)
            prompt_chunks = build_prompt_chunks(
                protocol_summary=protocol_summary,
                canonical_context=canonical_context,
                contributor=metadata["contributor"],
                branch=metadata["branch"],
                group=group,
            )

            for chunk_index, (chunk_changes, prompt_text) in enumerate(prompt_chunks, start=1):
                if args.dry_run:
                    prompt_path = write_prompt_preview(
                        prompt_dir=prompt_dir,
                        contributor=metadata["contributor"],
                        group_id=f"{group.group_id}-chunk-{chunk_index}",
                        chunk_index=chunk_index,
                        prompt_text=prompt_text,
                    )
                    prompt_files.append(str(prompt_path.resolve()))
                    log(
                        f"[DRY RUN] Prepared prompt group={group.group_id} "
                        f"chunk={chunk_index} chars={len(prompt_text)}"
                    )
                    if args.verbose:
                        log("--- PROMPT START ---")
                        log(prompt_text)
                        log("--- PROMPT END ---")
                    for change in chunk_changes:
                        all_decisions.append(dry_run_fallback_decision(change))
                    continue

                if duo_call_count > 0:
                    if args.verbose:
                        log(f"Sleeping {args.delay_seconds:.1f}s to respect Duo rate limits.")
                    time.sleep(args.delay_seconds)

                duo_call_count += 1
                response_text = call_duo(prompt_text=prompt_text, verbose=args.verbose)
                chunk_decisions: list[dict[str, object]]
                chunk_warnings: list[str]
                try:
                    chunk_decisions, chunk_warnings = parse_group_decisions(
                        duo_output=response_text,
                        expected_changes=chunk_changes,
                    )
                except ValueError as exc:
                    chunk_decisions = [
                        fallback_decision(change, "Failed to parse Duo response for this prompt chunk.")
                        for change in chunk_changes
                    ]
                    chunk_warnings = [str(exc)]
                all_decisions.extend(chunk_decisions)
                all_warnings.extend(chunk_warnings)

            log(f"Curating group {group.group_id}... done")
            if group_index < len(groups) - 1 and args.verbose:
                log("")

        report = build_report(metadata=metadata, decisions=all_decisions)
        json_report, markdown_report = write_report_files(
            output_dir=output_dir,
            contributor=metadata["contributor"],
            report=report,
        )

        if all_warnings:
            log("Warnings:")
            for warning in all_warnings:
                log(f"- {warning}")

        summary = report["metadata"]
        if not isinstance(summary, dict):
            raise RuntimeError("Invalid report metadata.")
        recommendation_summary = summary.get("by_recommendation", {})
        log(
            "Curation complete. "
            f"decisions={summary.get('total_decisions', 0)} "
            f"review_required={summary.get('requires_review_count', 0)} "
            f"accept={int(getattr(recommendation_summary, 'get', lambda *_: 0)('accept', 0))} "
            f"revise={int(getattr(recommendation_summary, 'get', lambda *_: 0)('revise', 0))} "
            f"reject={int(getattr(recommendation_summary, 'get', lambda *_: 0)('reject', 0))} "
            f"move={int(getattr(recommendation_summary, 'get', lambda *_: 0)('move', 0))} "
            f"prune={int(getattr(recommendation_summary, 'get', lambda *_: 0)('prune', 0))}"
        )

        payload = {
            "status": "ok",
            "dry_run": args.dry_run,
            "backend": "duo-cli",
            "diff_report": str(diff_report_path),
            "rootstock_repo": str(rootstock_repo),
            "output_dir": str(output_dir.resolve()),
            "json_report": str(json_report.resolve()),
            "markdown_report": str(markdown_report.resolve()),
            "prompt_preview_files": prompt_files,
            "metadata": summary,
        }
        emit_json(payload)
        return EXIT_SUCCESS
    except Exception as exc:  # noqa: BLE001
        return fail(str(exc), payload if payload else None)


if __name__ == "__main__":
    raise SystemExit(main())
